const drugImageMap = {
    "Acetal": "Reference/DrugData/Images/ACE4GB01.jpg",
    "Advagraf 1mg": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/ADV4NB46-A.jpg",
    "Akinfree": "Reference/DrugData/Images/AKN4JB01.jpg",
    "Aldactone": "Reference/DrugData/Images/ALD4DA06.jpg",
    "Aleviatin": "Reference/DrugData/Images/ALE4JA07.jpg",
    "Algitab": "Reference/DrugData/Images/TOP4HF28.jpg",
    "Amanda": "Reference/DrugData/Images/AMA4JB11.jpg",
    "Amaryl": "Reference/DrugData/Images/AMA4LB13.jpg",
    "Amoxicillin": "Reference/DrugData/Images/AMO4AA16-A.jpg",
    "Antiasth": "Reference/DrugData/Images/ANT4MA10.jpg",
    "Aprovel 300mg": "Reference/DrugData/Images/APR4DBF1.jpg",
    "Arcoxia": "Reference/DrugData/Images/ARC4GB65.jpg",
    "Arheuma": "Reference/DrugData/Images/ARH4NB22.jpg",
    "Atanaal 5mg": "Reference/DrugData/Images/AT%204DE11.jpg",
    "Ateol": "Reference/DrugData/Images/ATE4DB11.jpg",
    "Avodart": "Reference/DrugData/Images/AVO4DI19.jpg",
    "Azilect": "Reference/DrugData/Images/AZI4JB41.jpg",
    "Baktar": "Reference/DrugData/Images/BAK4AI02.jpg",
    "Baraclude 0.5mg": "Reference/DrugData/Images/BAR4AM43.jpg",
    "Betmiga": "Reference/DrugData/Images/BET4DI27.jpg",
    "Biofermin": "Reference/DrugData/Images/BIO4HD05.jpg",
    "Bokey": "Reference/DrugData/Images/BOK4EA38.jpg",
    "COZAAR": "Reference/DrugData/Images/COZ4DB62.jpg",
    "Calcium Carbonate": "Reference/DrugData/Images/ACA4JF42.jpg",
    "Carpine": "Reference/DrugData/Images/CAR4JA01.jpg",
    "Catilon": "Reference/DrugData/Images/CAT4HA49.jpg",
    "Celebrex": "Reference/DrugData/Images/CEL4GB58.jpg",
    "糖 Carlipin": "Reference/DrugData/Images/CAR4LB44-A.jpg",
    "CellCept": "Reference/DrugData/Images/CEL4NB19.jpg",
    "Certican": "Reference/DrugData/Images/CER4NB41.jpg",
    "Cofarin 1mg": "Reference/DrugData/Images/COA4EA03.jpg",
    "Concor 5": "Reference/DrugData/Images/CON4DB41.jpg",
    "Coxine": "Reference/DrugData/Images/COX4DE15.jpg",
    "Crestor": "Reference/DrugData/Images/CRE4FD29.jpg",
    "Curam": "Reference/DrugData/Images/CUR4AA35.jpg",
    "Cymbalta": "Reference/DrugData/Images/CYM4DI12.jpg",
    "DILATREND 6.25mg": "Reference/DrugData/Images/DIL4DB84-A.jpg",
    "DOXABEN XL 4MG": "Reference/DrugData/Images/DOX4DB97.jpg",
    "Denosin": "Reference/DrugData/Images/DEN4MD16-A.jpg",
    "Dexilant": "Reference/DrugData/Images/DEX4HA52.jpg",
    "Diamicron": "Reference/DrugData/Images/DIA4LB59.jpg",
    "Diovan 160mg": "Reference/DrugData/Images/DIO4DB23-C.jpg",
    "Diphenidol": "Reference/DrugData/Images/DIP4JE01.jpg",
    "Dosin": "Reference/DrugData/Images/DOS4HE22.jpg",
    "Doxaben 2mg": "Reference/DrugData/Images/DOX4DBD4-A.jpg",
    "Dulcolax": "Reference/DrugData/Images/DU%204HC01.jpg",
    "EURICON": "Reference/DrugData/Images/EUR4GC04-A.jpg",
    "Ezetrol": "Reference/DrugData/Images/EZE4FD26-C.jpg",
    "Edarbi": "Reference/DrugData/Images/EDA4DBB7.jpg",
    "Effexor 75": "Reference/DrugData/Images/EFE4IC21.jpg",
    "Eliquis": "Reference/DrugData/Images/ELI4EA49.jpg",
    "Entresto 50mg": "Reference/DrugData/Images/ENT4DBD1.jpg",
    "Escitalo": "Reference/DrugData/Images/ESC4IC15.jpg",
    "Exforge": "Reference/DrugData/Images/EXF4DBF0.jpg",
    "Feburic": "Reference/DrugData/Images/FEB4GC11.jpg",
    "Ferrum": "Reference/DrugData/Images/FER4EC23.jpg",
    "Folic acid": "Reference/DrugData/Images/FO_4EC22-A.jpg",
    "Fluitran": "Reference/DrugData/Images/FLU4DA08.jpg",
    "Folina": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/COV1QB04-A.jpg",
    "Forflow SR": "Reference/DrugData/Images/FOR4DH03.jpg",
    "Forxiga": "Reference/DrugData/Images/FOR4LB99.jpg",
    "Fycompa": "Reference/DrugData/Images/FYC4JA41.jpg",
    "Ginkgocentrate": "Reference/DrugData/Images/GIK4FB26.jpg",
    "Glucophage": "Reference/DrugData/Images/GLU4LB32.jpg",
    "Glunormal": "Reference/DrugData/Images/GLN4LB36.jpg",
    "Glyxambi": "Reference/DrugData/Images/GLY4LBA5.jpg",
    "HARNALIDGE": "Reference/DrugData/Images/HAR4DB19.jpg",
    "Harnalidge": "Reference/DrugData/Images/HAR4DB19.jpg",
    "Imolex": "Reference/DrugData/Images/IMO4HB09.jpg",
    "Isoptin SR": "Reference/DrugData/Images/ISO4DD14.jpg",
    "Januvia": "Reference/DrugData/Images/JAN4LB71.jpg",
    "Jardiance 25mg": "Reference/DrugData/Images/JAR4LB98-A.jpg",
    "Juxac": "Reference/DrugData/Images/JUX4IC06.jpg",
    "Kascoal": "Reference/DrugData/Images/KAS4HF05.jpg",
    "Keppra": "Reference/DrugData/Images/KEP1JA35.jpg",
    "Keppra FC 500 mg/tab": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/KEP4JA35-A.jpg",
    "Lasix": "Reference/DrugData/Images/LAS4DA03.jpg",
    "Lendormin": "Reference/DrugData/Images/LE%204IA19.jpg",
    "Lescol XL": "Reference/DrugData/Images/LES4FD32.jpg",
    "Lexotan": "Reference/DrugData/Images/LE%204IA01.jpg",
    "Lipanthyl": "Reference/DrugData/Images/LIP4FD33.jpg",
    "Lipitor": "Reference/DrugData/Images/LIP4FD35.jpg",
    "Livalo": "Reference/DrugData/Images/LIV4FD36.jpg",
    "Lixiana 30mg": "Reference/DrugData/Images/LIX4EA53.jpg",
    "Loditon": "Reference/DrugData/Images/LOD4LB57.jpg",
    "Lyrica": "Reference/DrugData/Images/LYR4JA38.jpg",
    "Meletin": "Reference/DrugData/Images/MEL4DD09.jpg",
    "Meptin": "Reference/DrugData/Images/MEP4MA19.jpg",
    "Mevalotin 40mg": "Reference/DrugData/Images/MEV4FD34.jpg",
    "MgO 28#": "Reference/DrugData/Images/MGO4HA04.jpg",
    "MgO 56#": "Reference/DrugData/Images/MGO4HA04.jpg",
    "Mirapex 1mg": "Reference/DrugData/Images/MIR4JB27.jpg",
    "Muaction": "Reference/DrugData/Images/MUA4GB44.jpg",
    "Musco": "Reference/DrugData/Images/MUS4MC02.jpg",
    "Myfortic": "Reference/DrugData/Images/MYF4NB35.jpg",
    "Nacid": "Reference/DrugData/Images/NAC4HA44.jpg",
    "Naposin": "Reference/DrugData/Images/NAP4GB09.jpg",
    "Natrilix": "Reference/DrugData/Images/NAT4DA44.jpg",
    "Nebilet": "Reference/DrugData/Images/NEB4DBD2.jpg",
    "Neuquinon": "Reference/DrugData/Images/NEU4DH02.jpg",
    "Nexium": "Reference/DrugData/Images/NEX4HA41.jpg",
    "Nifedipine 30mg": "Reference/DrugData/Images/NIF4DE12-A.jpg",
    "Nitrostat Sub.": "Reference/DrugData/Images/NIT4DE04.jpg",
    "Nolvadex": "Reference/DrugData/Images/NOL4CE01.jpg",
    "Norvasc": "Reference/DrugData/Images/NOR4DE18.jpg",
    "Olmetec": "Reference/DrugData/Images/OLM4DBE6.jpg",
    "Oxbu": "Reference/DrugData/Images/OXB4DI21.jpg",
    "PLAQUENIL": "Reference/DrugData/Images/PLA4BA05.jpg",
    "Pariet": "Reference/DrugData/Images/PAR4HA37.jpg",
    "Plavix": "Reference/DrugData/Images/PLA4DH21.jpg",
    "Pletaal": "Reference/DrugData/Images/PLE4DH26.jpg",
    "Pradaxa 110mg": "Reference/DrugData/Images/PRA4EA45.jpg",
    "Predonine": "Reference/DrugData/Images/PRE4LA09.jpg",
    "Prograf 1mg": "Reference/DrugData/Images/PRO4NB09.jpg",
    "Promeran": "Reference/DrugData/Images/PR%204HD04.jpg",
    "Qtern": "Reference/DrugData/Images/QTE4LBA7.jpg",
    "Regrow SR": "Reference/DrugData/Images/REG4MB12.jpg",
    "Requip 2mg": "Reference/DrugData/Images/REQ4JB31-C.jpg",
    "Rivotril": "Reference/DrugData/Images/RI%204JA09.jpg",
    "Rytmonorm": "Reference/DrugData/Images/RYT4DD23.jpg",
    "SOLAXIN": "Reference/DrugData/Images/SOL4JC01.jpg",
    "Sandel": "Reference/DrugData/Images/SAN4DE05.jpg",
    "Sandimmun 25": "Reference/DrugData/Images/SAN1NB04.jpg",
    "Sandimmun Neoral 25 mg/cap": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/SAN1NB04-A.jpg",
    "Secorin": "Reference/DrugData/Images/SEC4IA05.jpg",
    "Sennapur": "Reference/DrugData/Images/SEN4HC12.jpg",
    "Seroquel XR 200mg": "Reference/DrugData/Images/SER4IB24.jpg",
    "Seroquel XR 200 mg/tab": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/SER4IB42-A.jpg",
    "Sigmart": "Reference/DrugData/Images/SIG4DE03.jpg",
    "Singulair 10mg": "Reference/DrugData/Images/SIN4MA67.jpg",
    "Splotin 50mg": "Reference/DrugData/Images/SPL4IB12.jpg",
    "Stable 25": "Reference/DrugData/Images/STA4DB06.jpg",
    "Stable 25 mg/tab": "Reference/DrugData/Images/STA4DB06.jpg",
    "Stilnox": "Reference/DrugData/Images/STI4IA32.jpg",
    "Strocain": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/STR4HA05-A.jpg",
    "Sulpin 200mg": "Reference/DrugData/Images/SUL4IB11.jpg",
    "Suzin": "Reference/DrugData/Images/SUZ4GD04.jpg",
    "Syntam": "Reference/DrugData/Images/SYN4ID08.jpg",
    "Trajenta": "Reference/DrugData/Images/TRA4LB89.jpg",
    "Trileptal": "Reference/DrugData/Images/TRI4JA31-A.jpg",
    "Urief": "Reference/DrugData/Images/URI4DI26.jpg",
    "Utrogestan": "Reference/DrugData/Images/UT%204LF01.jpg",
    "Vimpat": "Reference/DrugData/Images/VIM1JA42.jpg",
    "Visanne": "Reference/DrugData/Images/VIS4LF60.jpg",
    "Vit. B C 28#": "Reference/DrugData/Images/VIT1FB02.jpg",
    "Votan": "Reference/DrugData/Images/VOT4GB41.jpg",
    "Weimok": "Reference/DrugData/Images/WEI4HA48.jpg",
    "Xyzal": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/XYZ4MD40-A.jpg",
    "Youkoxia": "Reference/DrugData/Images/YOU4GB65-A.jpg",
    "Zanidip": "Reference/DrugData/Images/ZAN4DB91.jpg",
    "Zoloft": "Reference/DrugData/Images/ZOL4IC09.jpg",
    "Zyprexa": "Reference/DrugData/Images/ZYP4IB41-A.jpg",
    "新 Pronolol": "Reference/DrugData/Images/NEO4SD35.jpg",
    "Alpraline": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/ALP4IA13-A.jpg",
    "Apa-Mirtazapine ODT": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/APA4IC26-A.jpg",
    "Artelac oph.": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/ART2UD06-A.jpg",
    "Aspirin": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/ASP4GB14-A.jpg",
    "Ativan": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/ATI4IA10-A.jpg",
    "Biocal": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/BIO4FAJ5-A.jpg",
    "C.B. Strong": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/CBS7SA31-A.jpg",
    "Catapress": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/CA%204DB01-A.jpg",
    "Cephalexin": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/CEP4AB02-A.jpg",
    "Cinnazine": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/CIN4DF01-A.jpg",
    "Clozaril": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/CLO4IB17-A.jpg",
    "Colchicine": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/COL4GC09-A.jpg",
    "Colian": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/COL4IC08-A.jpg",
    "Comtan": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/COM4JB25-A.jpg",
    "Cordarone": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/COR1DD10-B.jpg",
    "Depakine": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/DEP1JA15-A.jpg",
    "Doxymycin": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/DOX4AE01-A.jpg",
    "ESTRADE": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/EST4LF27-A.jpg",
    "Epram": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/EPR4IC15-A.jpg",
    "Eurodin": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/EUR4IA03-A.jpg",
    "Femara": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/FEM4CB22-A.jpg",
    "Foxone oph.": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/FOX2UC04-A.jpg",
    "Herbesser": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/HER1DE19-A.jpg",
    "Imovane": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/IMO4IA27-A.jpg",
    "LAMICTAL": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/LAM4JA23-A.jpg",
    "Madopar": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MA%204JB06-A.jpg",
    "Mesyrel": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MES4IC13-A.jpg",
    "Methacin gel": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MET7SA25-A.jpg",
    "Methycobal": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MET4FB18-A.jpg",
    "Methylcobal": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MET4FB18-A.jpg",
    "Midorine": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MID4DG20-A.jpg",
    "Mobicam": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MOP4GB60-A.jpg",
    "Mopride": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MOP4HF02-A.jpg",
    "Nincort": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/NIN2RA25-A.jpg",
    "O.N.S.D.": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/ONS2UD04-A.jpg",
    "Pacrea": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/PAC4HD15-A.jpg",
    "Procal": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/PRO4FAC8-A.jpg",
    "Repaglinide": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/REP4LB06-A.jpg",
    "Rinderon-V": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/RIN7SG01-A.jpg",
    "Salazine": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/SA%204AI11-B.jpg",
    "Seroquel 25mg": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/SER4IB24-A.jpg",
    "Simethicone": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/WIL5HF14-B.jpg",
    "Solian": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/SOL4IB22-A.jpg",
    "Somatosan": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/SOM1LD13-A.jpg",
    "Tegretol 200mg": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/TEG4JA22-A.jpg",
    "Tofranil": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/TO%204IC04-A.jpg",
    "Trandate": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/TRA1DB18-A.jpg",
    "Transamin 250 mg/cap": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/TRA4EB10-A.jpg",
    "U-Ca": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/UCA4FB23-A.jpg",
    "Uroso": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/URO4FE10-A.jpg",
    "Utraphen": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/UTR4GB63-A.jpg",
    "Acemet": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/ACE4GB57-A.jpg",
    "Actos": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/AC%204LB42-A.jpg",
    "Alfacalcidol": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/ALC4FB16-A.jpg",
    "Allegra": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/s/ALL4MD36-A.jpg",
    "Syntocinon": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/OXY1LG01-A.jpg",
    "Tapal": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/ASP4BF02-G.jpg",
    "Uroscan": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/URO1PA08-B.jpg",
    "Vena": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/DI%201MD06-A.jpg",
    "Witgen": "https://reg.ntuh.gov.tw/pharmacyoutside/DrugImage/New/MAN4JF22-A.jpg",
};
