const drugImageMap = {
    "Acetal": "Reference/DrugData/Images/ACE4GB01.jpg",
    "Advagraf 1mg": "Reference/DrugData/Images/ADV4NB46.jpg",
    "Akinfree": "Reference/DrugData/Images/AKN4JB01.jpg",
    "Aldactone": "Reference/DrugData/Images/ALD4DA06.jpg",
    "Aleviatin": "Reference/DrugData/Images/ALE4JA07.jpg",
    "Algitab": "Reference/DrugData/Images/TOP4HF28.jpg",
    "Amanda": "Reference/DrugData/Images/AMA4JB11.jpg",
    "Amaryl": "Reference/DrugData/Images/AMA4LB13.jpg",
    "Amoxicillin": "Reference/DrugData/Images/AMO4AA16-A.jpg",
    "Antiasth": "Reference/DrugData/Images/ANT4MA10.jpg",
    "Aprovel 300mg": "Reference/DrugData/Images/APR4DBF1.jpg",
    "Arcoxia": "Reference/DrugData/Images/ARC4GB65.jpg",
    "Arheuma": "Reference/DrugData/Images/ARH4NB22.jpg",
    "Atanaal 5mg": "Reference/DrugData/Images/AT%204DE11.jpg",
    "Ateol": "Reference/DrugData/Images/ATE4DB11.jpg",
    "Avodart": "Reference/DrugData/Images/AVO4DI19.jpg",
    "Azilect": "Reference/DrugData/Images/AZI4JB41.jpg",
    "Baktar": "Reference/DrugData/Images/BAK4AI02.jpg",
    "Baraclude 0.5mg": "Reference/DrugData/Images/BAR4AM43.jpg",
    "Betmiga": "Reference/DrugData/Images/BET4DI27.jpg",
    "Biofermin": "Reference/DrugData/Images/BIO4HD05.jpg",
    "Bokey": "Reference/DrugData/Images/BOK4EA38.jpg",
    "COZAAR": "Reference/DrugData/Images/COZ4DB62.jpg",
    "Calcium Carbonate": "Reference/DrugData/Images/ACA4JF42.jpg",
    "Carpine": "Reference/DrugData/Images/CAR4JA01.jpg",
    "Catilon": "Reference/DrugData/Images/CAT4HA49.jpg",
    "Celebrex": "Reference/DrugData/Images/CEL4GB58.jpg",
    "糖 Carlipin": "Reference/DrugData/Images/CAR4LB44-A.jpg",
    "CellCept": "Reference/DrugData/Images/CEL4NB19.jpg",
    "Certican": "Reference/DrugData/Images/CER4NB41.jpg",
    "Cofarin 1mg": "Reference/DrugData/Images/COA4EA03.jpg",
    "Concor 5": "Reference/DrugData/Images/CON4DB41.jpg",
    "Coxine": "Reference/DrugData/Images/COX4DE15.jpg",
    "Crestor": "Reference/DrugData/Images/CRE4FD29.jpg",
    "Curam": "Reference/DrugData/Images/CUR4AA35.jpg",
    "Cymbalta": "Reference/DrugData/Images/CYM4DI12.jpg",
    "DILATREND 6.25mg": "Reference/DrugData/Images/DIL4DB84-A.jpg",
    "DOXABEN XL 4MG": "Reference/DrugData/Images/DOX4DB97.jpg",
    "Denosin": "Reference/DrugData/Images/DEN4MD16-A.jpg",
    "Dexilant": "Reference/DrugData/Images/DEX4HA52.jpg",
    "Diamicron": "Reference/DrugData/Images/DIA4LB59.jpg",
    "Diovan 160mg": "Reference/DrugData/Images/DIO4DB23-C.jpg",
    "Diphenidol": "Reference/DrugData/Images/DIP4JE01.jpg",
    "Dosin": "Reference/DrugData/Images/DOS4HE22.jpg",
    "Doxaben 2mg": "Reference/DrugData/Images/DOX4DBD4-A.jpg",
    "Dulcolax": "Reference/DrugData/Images/DU%204HC01.jpg",
    "EURICON": "Reference/DrugData/Images/EUR4GC04-A.jpg",
    "Ezetrol": "Reference/DrugData/Images/EZE4FD26-C.jpg",
    "Edarbi": "Reference/DrugData/Images/EDA4DBB7.jpg",
    "Effexor 75": "Reference/DrugData/Images/EFE4IC21.jpg",
    "Eliquis": "Reference/DrugData/Images/ELI4EA49.jpg",
    "Entresto 50mg": "Reference/DrugData/Images/ENT4DBD1.jpg",
    "Escitalo": "Reference/DrugData/Images/ESC4IC15.jpg",
    "Exforge": "Reference/DrugData/Images/EXF4DBF0.jpg",
    "Feburic": "Reference/DrugData/Images/FEB4GC11.jpg",
    "Ferrum": "Reference/DrugData/Images/FER4EC23.jpg",
    "Folic acid": "Reference/DrugData/Images/FO_4EC22-A.jpg",
    "Fluitran": "Reference/DrugData/Images/FLU4DA08.jpg",
    "Folina": "Reference/DrugData/Images/COV1QB04.jpg",
    "Forflow SR": "Reference/DrugData/Images/FOR4DH03.jpg",
    "Forxiga": "Reference/DrugData/Images/FOR4LB99.jpg",
    "Fycompa": "Reference/DrugData/Images/FYC4JA41.jpg",
    "Ginkgocentrate": "Reference/DrugData/Images/GIK4FB26.jpg",
    "Glucophage": "Reference/DrugData/Images/GLU4LB32.jpg",
    "Glunormal": "Reference/DrugData/Images/GLN4LB36.jpg",
    "Glyxambi": "Reference/DrugData/Images/GLY4LBA5.jpg",
    "HARNALIDGE": "Reference/DrugData/Images/HAR4DB19.jpg",
    "Harnalidge": "Reference/DrugData/Images/HAR4DB19.jpg",
    "Imolex": "Reference/DrugData/Images/IMO4HB09.jpg",
    "Isoptin SR": "Reference/DrugData/Images/ISO4DD14.jpg",
    "Januvia": "Reference/DrugData/Images/JAN4LB71.jpg",
    "Jardiance 25mg": "Reference/DrugData/Images/JAR4LB98-A.jpg",
    "Juxac": "Reference/DrugData/Images/JUX4IC06.jpg",
    "Kascoal": "Reference/DrugData/Images/KAS4HF05.jpg",
    "Keppra": "Reference/DrugData/Images/KEP1JA35.jpg",
    "Keppra FC 500 mg/tab": "Reference/DrugData/Images/KEP1JA35.jpg",
    "Lasix": "Reference/DrugData/Images/LAS4DA03.jpg",
    "Lendormin": "Reference/DrugData/Images/LE%204IA19.jpg",
    "Lescol XL": "Reference/DrugData/Images/LES4FD32.jpg",
    "Lexotan": "Reference/DrugData/Images/LE%204IA01.jpg",
    "Lipanthyl": "Reference/DrugData/Images/LIP4FD33.jpg",
    "Lipitor": "Reference/DrugData/Images/LIP4FD35.jpg",
    "Livalo": "Reference/DrugData/Images/LIV4FD36.jpg",
    "Lixiana 30mg": "Reference/DrugData/Images/LIX4EA53.jpg",
    "Loditon": "Reference/DrugData/Images/LOD4LB57.jpg",
    "Lyrica": "Reference/DrugData/Images/LYR4JA38.jpg",
    "Meletin": "Reference/DrugData/Images/MEL4DD09.jpg",
    "Meptin": "Reference/DrugData/Images/MEP4MA19.jpg",
    "Mevalotin 40mg": "Reference/DrugData/Images/MEV4FD34.jpg",
    "MgO 28#": "Reference/DrugData/Images/MGO4HA04.jpg",
    "MgO 56#": "Reference/DrugData/Images/MGO4HA04.jpg",
    "Mirapex 1mg": "Reference/DrugData/Images/MIR4JB27.jpg",
    "Muaction": "Reference/DrugData/Images/MUA4GB44.jpg",
    "Musco": "Reference/DrugData/Images/MUS4MC02.jpg",
    "Myfortic": "Reference/DrugData/Images/MYF4NB35.jpg",
    "Nacid": "Reference/DrugData/Images/NAC4HA44.jpg",
    "Naposin": "Reference/DrugData/Images/NAP4GB09.jpg",
    "Natrilix": "Reference/DrugData/Images/NAT4DA44.jpg",
    "Nebilet": "Reference/DrugData/Images/NEB4DBD2.jpg",
    "Neuquinon": "Reference/DrugData/Images/NEU4DH02.jpg",
    "Nexium": "Reference/DrugData/Images/NEX4HA41.jpg",
    "Nifedipine 30mg": "Reference/DrugData/Images/NIF4DE12-A.jpg",
    "Nitrostat Sub.": "Reference/DrugData/Images/NIT4DE04.jpg",
    "Nolvadex": "Reference/DrugData/Images/NOL4CE01.jpg",
    "Norvasc": "Reference/DrugData/Images/NOR4DE18.jpg",
    "Olmetec": "Reference/DrugData/Images/OLM4DBE6.jpg",
    "Oxbu": "Reference/DrugData/Images/OXB4DI21.jpg",
    "PLAQUENIL": "Reference/DrugData/Images/PLA4BA05.jpg",
    "Pariet": "Reference/DrugData/Images/PAR4HA37.jpg",
    "Plavix": "Reference/DrugData/Images/PLA4DH21.jpg",
    "Pletaal": "Reference/DrugData/Images/PLE4DH26.jpg",
    "Pradaxa 110mg": "Reference/DrugData/Images/PRA4EA45.jpg",
    "Predonine": "Reference/DrugData/Images/PRE4LA09.jpg",
    "Prograf 1mg": "Reference/DrugData/Images/PRO4NB09.jpg",
    "Promeran": "Reference/DrugData/Images/PR%204HD04.jpg",
    "Qtern": "Reference/DrugData/Images/QTE4LBA7.jpg",
    "Regrow SR": "Reference/DrugData/Images/REG4MB12.jpg",
    "Requip 2mg": "Reference/DrugData/Images/REQ4JB31-C.jpg",
    "Rivotril": "Reference/DrugData/Images/RI%204JA09.jpg",
    "Rytmonorm": "Reference/DrugData/Images/RYT4DD23.jpg",
    "SOLAXIN": "Reference/DrugData/Images/SOL4JC01.jpg",
    "Sandel": "Reference/DrugData/Images/SAN4DE05.jpg",
    "Sandimmun 25": "Reference/DrugData/Images/SAN1NB04.jpg",
    "Sandimmun Neoral 25 mg/cap": "Reference/DrugData/Images/SAN1NB04.jpg",
    "Secorin": "Reference/DrugData/Images/SEC4IA05.jpg",
    "Sennapur": "Reference/DrugData/Images/SEN4HC12.jpg",
    "Seroquel XR 200mg": "Reference/DrugData/Images/SER4IB24.jpg",
    "Seroquel XR 200 mg/tab": "Reference/DrugData/Images/SER4IB24.jpg",
    "Sigmart": "Reference/DrugData/Images/SIG4DE03.jpg",
    "Singulair 10mg": "Reference/DrugData/Images/SIN4MA67.jpg",
    "Splotin 50mg": "Reference/DrugData/Images/SPL4IB12.jpg",
    "Stable 25": "Reference/DrugData/Images/STA4DB06.jpg",
    "Stable 25 mg/tab": "Reference/DrugData/Images/STA4DB06.jpg",
    "Stilnox": "Reference/DrugData/Images/STI4IA32.jpg",
    "Strocain": "Reference/DrugData/Images/STR4HA05.jpg",
    "Sulpin 200mg": "Reference/DrugData/Images/SUL4IB11.jpg",
    "Suzin": "Reference/DrugData/Images/SUZ4GD04.jpg",
    "Syntam": "Reference/DrugData/Images/SYN4ID08.jpg",
    "Trajenta": "Reference/DrugData/Images/TRA4LB89.jpg",
    "Trileptal": "Reference/DrugData/Images/TRI4JA31-A.jpg",
    "Urief": "Reference/DrugData/Images/URI4DI26.jpg",
    "Utrogestan": "Reference/DrugData/Images/UT%204LF01.jpg",
    "Vimpat": "Reference/DrugData/Images/VIM1JA42.jpg",
    "Visanne": "Reference/DrugData/Images/VIS4LF60.jpg",
    "Vit. B C 28#": "Reference/DrugData/Images/VIT1FB02.jpg",
    "Votan": "Reference/DrugData/Images/VOT4GB41.jpg",
    "Weimok": "Reference/DrugData/Images/WEI4HA48.jpg",
    "Xyzal": "Reference/DrugData/Images/XYZ4MD40.jpg",
    "Youkoxia": "Reference/DrugData/Images/YOU4GB65-A.jpg",
    "Zanidip": "Reference/DrugData/Images/ZAN4DB91.jpg",
    "Zoloft": "Reference/DrugData/Images/ZOL4IC09.jpg",
    "Zyprexa": "Reference/DrugData/Images/ZYP4IB41-A.jpg",
    "新 Pronolol": "Reference/DrugData/Images/NEO4SD35.jpg"
};
